
# Group Handlers

## /account/{address}

+ Parameters
    + address: `7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0` (string)

### Query Account [GET]
is to query an account by address


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "height": 1755516,
  "data": {
    "coins": [
      {
        "denom": "fermion",
        "amount": 4
      }
    ],
    "credit": []
  }
}
        



## /account/{address}/tx/coin

+ Parameters
    + address: `7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0` (string)

### Search Coin Tx By Account [GET]
is to search for
all SendTx transactions with this account as sender
or receiver


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "height": 178507,
    "tx": {
      "type": "fee/tx",
      "data": {
        "fee": {
          "denom": "fermion",
          "amount": 1
        },
        "payer": {
          "chain": "",
          "app": "sigs",
          "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
        },
        "tx": {
          "type": "coin/send",
          "data": {
            "inputs": [
              {
                "address": {
                  "chain": "",
                  "app": "sigs",
                  "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
                },
                "coins": [
                  {
                    "denom": "fermion",
                    "amount": 2
                  }
                ]
              }
            ],
            "outputs": [
              {
                "address": {
                  "chain": "",
                  "app": "sigs",
                  "addr": "6A9AEA0331598799D5F009EC9B7D635BB8F34EFF"
                },
                "coins": [
                  {
                    "denom": "fermion",
                    "amount": 2
                  }
                ]
              }
            ]
          }
        }
      }
    },
    "txhash": "83527AC99E577CEF7408FA8BD2F660F7D95C69BC"
  },
  {
    "height": 178071,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 1
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "6A9AEA0331598799D5F009EC9B7D635BB8F34EFF"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 1
              }
            ]
          }
        ]
      }
    },
    "txhash": "9C62C9AB93664ECB7162683537CF9C028EF8C262"
  },
  {
    "height": 66804,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 2
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "D3EEBDF9593BE3D3C0B249DB56A9E45DC490FE97"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 2
              }
            ]
          }
        ]
      }
    },
    "txhash": "76E8027FD93F83892A3204B01CCE0FC6FED3563D"
  },
  {
    "height": 10546,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ]
      }
    },
    "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
  }
]
        



## /block/{height}

+ Parameters
    + height: `10546` (number)

### Query Block [GET]
is to query a block by height


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "block_meta": {
    "block_id": {
      "hash": "F78FF304909587F77A52D5900367783F69A4FAAD",
      "parts": {
        "total": 1,
        "hash": "5DCA1BA2A87A084EB1CEFA7D145BEAA4A027C320"
      }
    },
    "header": {
      "chain_id": "gaia-2",
      "height": 10546,
      "time": "2018-01-06T11:53:54.522-05:00",
      "num_txs": 1,
      "last_block_id": {
        "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
        "parts": {
          "total": 1,
          "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
        }
      },
      "total_txs": 10,
      "last_commit_hash": "1952C539B87606ADF893DD8A87002A0681946597",
      "data_hash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C",
      "validators_hash": "EE5F3404034C524501629B56E0DDC38FAD651F04",
      "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
      "app_hash": "FB3044CF1112AB6D8CA02FE712848A7BF990DB4A",
      "last_results_hash": "",
      "evidence_hash": ""
    }
  },
  "block": {
    "header": {
      "chain_id": "gaia-2",
      "height": 10546,
      "time": "2018-01-06T11:53:54.522-05:00",
      "num_txs": 1,
      "last_block_id": {
        "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
        "parts": {
          "total": 1,
          "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
        }
      },
      "total_txs": 10,
      "last_commit_hash": "1952C539B87606ADF893DD8A87002A0681946597",
      "data_hash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C",
      "validators_hash": "EE5F3404034C524501629B56E0DDC38FAD651F04",
      "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
      "app_hash": "FB3044CF1112AB6D8CA02FE712848A7BF990DB4A",
      "last_results_hash": "",
      "evidence_hash": ""
    },
    "data": {
      "txs": [
        "FgMBBmdhaWEtMgAAAAAAAAAAaQAAAAcBAQABBHNpZ3MBFPddD9cDaju5CS3Qk4u/CpMjIkgyIAEBAAEEc2lncwEU910P1wNqO7kJLdCTi78KkyMiSDIBAQEHZmVybWlvbgAAAAAAAAAKAQEAAQRzaWdzARRzNKSyZo3hzvDdfbppXClEnsOg0AEBAQdmZXJtaW9uAAAAAAAAAAoB9mnxY8p7rY5WQGP1dSCQbBUQJWQWttCihCHNQB4HH/Sj/8jIPDd2C+bP0lLSiUCSZwnHI90BDlSZU+MAX/kYCAFoagADN5j/oUsAwbIHw9rfQq0SL6X5ydSpvu24J+qZlA=="
      ]
    },
    "evidence": {
      "evidence": []
    },
    "last_commit": {
      "blockID": {
        "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
        "parts": {
          "total": 1,
          "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
        }
      },
      "precommits": [
        {
          "validator_address": "3294678052AAD1648F6E0AFBCECE3BD09B402CB1",
          "validator_index": 0,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.084-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "3FC160B1DC1FEC8518F8272D10BDBE898A1AC2CEDDB7ADC699B5781D943BFA97FCCBB98196F54C1A3A6A22DB2130E88D547794EA376609A27E9E5BAB7931D106"
          }
        },
        {
          "validator_address": "600AD8E3023710167C242AD1D26C4FB7AD3A3A39",
          "validator_index": 1,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.025-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "C767A4DAEE0BE3B69D8F4288C39D2EF1A96893B32DFAFBFA762F5E755A7E4E94324F7D97D2FB67FF3BAF8BB700D3959C0805816A1ECDC87CF83B2C565CF82302"
          }
        },
        {
          "validator_address": "898766AF03F350D117657A7E44E54D92423F9E83",
          "validator_index": 2,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.072-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "6D88CA3FD8FFB12A548B47492296D2966E6E011285FC5342C73401A05FBD7EB5CBF9D86FA75BE0E9E0AB91CC624FA36838C1DA57B3848CDA47FB9836A4AC2E00"
          }
        },
        {
          "validator_address": "CA956F20A083A26BF5B9C766E95D246E0624EDC6",
          "validator_index": 3,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.003-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "0F8DE68BFBE6D2CF4F736111BAD526B5F68836A0E57F7E802E51548937A7F703405C43CCF69A3CEB27271DCA459CA9A0CCF3507A017C7BC6A39C98E1A175A806"
          }
        },
        {
          "validator_address": "DC321F5C8DD94234903B53D44C1CF3B37B817950",
          "validator_index": 4,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.024-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "B96A4F40BEDC0083C41CD3670D31B8BE13C74DD2D60B829D4D09DF4B274A30BE2FD4DACA1F1FC6A813D9B9F9F76623AD071A1BBD53B374BA9A283F57AFCDDE05"
          }
        },
        {
          "validator_address": "DD59852B326AB9AC57E3A8CAF4F00459A9539970",
          "validator_index": 5,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.106-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "DD9780B51D0404D89ADE2340967069309FE776FDD7DBF063870FDCABF440E0F2A56D5EBEC5DD1327A5C55286BB86353CA4B6A01821B95E3ED30E42748BDF6C0E"
          }
        },
        {
          "validator_address": "E99FA5A12168E0C4194F1324866164331A1AC2C0",
          "validator_index": 6,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-06T11:53:36.065-05:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "71ED7A8A7A2D820D46D45435AB3EEBE8CCA5EE5E82DFC8770BE3A2FE00A2FAF54F19143831C3F4364C68BB68FAD72CC6C09418D5828EDAC22BAF4DA42C1FC701"
          }
        }
      ]
    }
  }
}
        



## /block/{height}/tx

+ Parameters
    + height: `10546` (number)

### Search Tx By Block [GET]
is to search for inner transaction by block height


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "height": 10546,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ]
      }
    },
    "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
  }
]
        



## /blocks/recent

### Query Recent Blocks [GET]
is to query recent 20 blocks


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "last_height": 1755517,
  "block_metas": [
    {
      "block_id": {
        "hash": "CA6784C6B8B64041843593A21C4E4F0CF857FBC2",
        "parts": {
          "total": 1,
          "hash": "E9247E764AF47503A148FD9747056BB2859779AD"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755517,
        "time": "2018-02-15T15:58:17.375-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "964DD3D0729D24599741068AC925AE780A83C498",
          "parts": {
            "total": 1,
            "hash": "DE13778C27143CDAE56B3E54F5896E8F83370BF5"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "F68F0848C831B76ECD8E53D36CB6D307100AB3A5",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "2AEE1A9DF0CB0A539253FCD291E2AE9B09285D26",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "964DD3D0729D24599741068AC925AE780A83C498",
        "parts": {
          "total": 1,
          "hash": "DE13778C27143CDAE56B3E54F5896E8F83370BF5"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755516,
        "time": "2018-02-15T15:58:15.669-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "446E1EFD5A0E9A444BBC7B2E1A60143017D770F8",
          "parts": {
            "total": 1,
            "hash": "ADFDFB00AF7EF47E5C303BA3D15CBEB540A9BF0B"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "07AC055C387AE94C9A43660DF4C1F965E7C408F2",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "1512E163CAAF72DA5C05D66B9E1A67F8F654BB7F",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "446E1EFD5A0E9A444BBC7B2E1A60143017D770F8",
        "parts": {
          "total": 1,
          "hash": "ADFDFB00AF7EF47E5C303BA3D15CBEB540A9BF0B"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755515,
        "time": "2018-02-15T15:58:13.801-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "00459EDE9779A98A588E0739080F6E778CBE7D61",
          "parts": {
            "total": 1,
            "hash": "FCDA5058E1BFF19E9CEB197C601FDA9E47927C52"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "A49CD51E22CEF093F81834B26F64180B38284755",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "8E63ECD35E8E25855002DFEEC1271427A89B304F",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "00459EDE9779A98A588E0739080F6E778CBE7D61",
        "parts": {
          "total": 1,
          "hash": "FCDA5058E1BFF19E9CEB197C601FDA9E47927C52"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755514,
        "time": "2018-02-15T15:58:11.991-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "5B438973D11A374DE28A579D8DB18F8C91E4AA31",
          "parts": {
            "total": 1,
            "hash": "60924DAA75798CE48A76ACE147A1B23EC2C20DF5"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "B9EE6DBC1628A95F0D848BC2A1093C5D179AD0FD",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "278A35BBA924724CB881FA804D44740F6712E34B",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "5B438973D11A374DE28A579D8DB18F8C91E4AA31",
        "parts": {
          "total": 1,
          "hash": "60924DAA75798CE48A76ACE147A1B23EC2C20DF5"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755513,
        "time": "2018-02-15T15:58:06.516-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "529885913CFA17BCB4BC70EEBB9CEE4A93EA7A1E",
          "parts": {
            "total": 1,
            "hash": "E55C48BEB164724DDB06732318672136FBA058AA"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "B6852337A5CEAA1326328403BA8DCA2B842416FD",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "85366EEE1123FC476020A28CD424BC38832F2F49",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "529885913CFA17BCB4BC70EEBB9CEE4A93EA7A1E",
        "parts": {
          "total": 1,
          "hash": "E55C48BEB164724DDB06732318672136FBA058AA"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755512,
        "time": "2018-02-15T15:58:04.775-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "0A98B4AF6CBE46E67CE003A319B2C126189D9BA3",
          "parts": {
            "total": 1,
            "hash": "B43203850832952EDC91F02F0A92D620B50F1957"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "983278047438CBAB2F9C98E04D803D0B7BE23542",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "708C883B9542F3EEEF680173BCECD8AC1C692586",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "0A98B4AF6CBE46E67CE003A319B2C126189D9BA3",
        "parts": {
          "total": 1,
          "hash": "B43203850832952EDC91F02F0A92D620B50F1957"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755511,
        "time": "2018-02-15T15:57:59.367-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "86C4F65EFEC36231688C91F40919634E72ED4E9F",
          "parts": {
            "total": 1,
            "hash": "F1E936A131A3650C6CFBFED0C7ACE6F5AAA797FD"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "E5BB34AADACD6262A0BA8715A8D7C82DFC3E1138",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "BE6EF28DC4CF99238A92DA8D85017B49B3F4C82F",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "86C4F65EFEC36231688C91F40919634E72ED4E9F",
        "parts": {
          "total": 1,
          "hash": "F1E936A131A3650C6CFBFED0C7ACE6F5AAA797FD"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755510,
        "time": "2018-02-15T15:57:57.538-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "6817DCBA1A38D18D28279BF4B0BBF4DB592B7566",
          "parts": {
            "total": 1,
            "hash": "11E4EEEE822C5D4BDC236A38042853A2F14B1B32"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "B57B88868298CDDE3E50B1C4F63DA60AB09E9C00",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "37190C32666565879E70501DC0A53FDDC7E83079",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "6817DCBA1A38D18D28279BF4B0BBF4DB592B7566",
        "parts": {
          "total": 1,
          "hash": "11E4EEEE822C5D4BDC236A38042853A2F14B1B32"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755509,
        "time": "2018-02-15T15:57:55.644-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "54C73E1A4A8DDA9FE39D967051228F2C31A2C039",
          "parts": {
            "total": 1,
            "hash": "73326CB8674E7ED15C7FE86A33FABDE8F50432BD"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "37899845293DA50ECB900C8C0964655188EAD862",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "648170FDC69CDC3A12CB6F5A33DB160EB1D0B970",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "54C73E1A4A8DDA9FE39D967051228F2C31A2C039",
        "parts": {
          "total": 1,
          "hash": "73326CB8674E7ED15C7FE86A33FABDE8F50432BD"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755508,
        "time": "2018-02-15T15:57:53.839-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "4D0329D8EF6B1067DF1EBC8D404607BBF9610D95",
          "parts": {
            "total": 1,
            "hash": "A50B5149B5A829A032AE91C3056A4E6D1FAC1A05"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "3D606E15BAF5978A5A8F917E8953AD0397F1A929",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "D33C76397AA9009A789FCD63E891F6DB5B14895D",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "4D0329D8EF6B1067DF1EBC8D404607BBF9610D95",
        "parts": {
          "total": 1,
          "hash": "A50B5149B5A829A032AE91C3056A4E6D1FAC1A05"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755507,
        "time": "2018-02-15T15:57:51.987-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "D24DEF5BB374B209FCEE54EC0760392D616A32D3",
          "parts": {
            "total": 1,
            "hash": "D422C4BEC246477B34F0575F7EA446DCAD5B4510"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "DBFD9E647B9FDBE47DE2DBC8151AD29CF0C68B2B",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "5C710F1DEE71CA8A7DF9A563284B7A28D3DD7F7D",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "D24DEF5BB374B209FCEE54EC0760392D616A32D3",
        "parts": {
          "total": 1,
          "hash": "D422C4BEC246477B34F0575F7EA446DCAD5B4510"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755506,
        "time": "2018-02-15T15:57:50.255-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "E765C91358E693185E5761D23D29CF8308E7D40E",
          "parts": {
            "total": 1,
            "hash": "484AD3642756AF82BEF10BF74311A778D8D77865"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "A85D87C9D8EB4F1A01EB7BCDAD8887F7AA0C8734",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "16191B53C26C5E5C6D77054CB87E3748C8F05B77",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "E765C91358E693185E5761D23D29CF8308E7D40E",
        "parts": {
          "total": 1,
          "hash": "484AD3642756AF82BEF10BF74311A778D8D77865"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755505,
        "time": "2018-02-15T15:57:44.817-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "0B57F467FCE4727EFDAC1ABB4C7D624CF77D2B70",
          "parts": {
            "total": 1,
            "hash": "068F86A92C1EEF54C481DCBCE1376D1B87DEAAC6"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "F68BD251588CF43E17C892CB367AD0A3AF3E2F2B",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "460BD8E8C3F7CC0E7023CDC79F929223B239B420",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "0B57F467FCE4727EFDAC1ABB4C7D624CF77D2B70",
        "parts": {
          "total": 1,
          "hash": "068F86A92C1EEF54C481DCBCE1376D1B87DEAAC6"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755504,
        "time": "2018-02-15T15:57:35.609-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "A7C5D2276AA0E1002C50CDCDCD373BE529A47F58",
          "parts": {
            "total": 1,
            "hash": "16142AE0D754266975ABA325432CA87D9C74864B"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "342979BDB7507842535EE96ED66E19B65C69CAAA",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "C353DDD14031DD9E716A855A4F76111AE19993A6",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "A7C5D2276AA0E1002C50CDCDCD373BE529A47F58",
        "parts": {
          "total": 1,
          "hash": "16142AE0D754266975ABA325432CA87D9C74864B"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755503,
        "time": "2018-02-15T15:57:21.969-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "85C158A193A762E94B8EE8F17B68130FB2E23A81",
          "parts": {
            "total": 1,
            "hash": "D07BF827E062972FD4DD5D029BBBF5AA787C55F4"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "22226D36848E21FD9E86A8BB57F23FE1617863BC",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "05EDD0C228ADFD6EC01CE864B3D3130865551A72",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "85C158A193A762E94B8EE8F17B68130FB2E23A81",
        "parts": {
          "total": 1,
          "hash": "D07BF827E062972FD4DD5D029BBBF5AA787C55F4"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755502,
        "time": "2018-02-15T15:57:20-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "79B9DCC20384ED8F4EBCEEF2C5D865E5D02AEBC4",
          "parts": {
            "total": 1,
            "hash": "B66F90970DC7BB28D49DB459C15CF06CCDB48950"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "9066C9B45AF0ED82C8E64CBD597ABA406B926288",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "2D0C3F40298EF0BDB25E35AB2B70328BEB03E320",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "79B9DCC20384ED8F4EBCEEF2C5D865E5D02AEBC4",
        "parts": {
          "total": 1,
          "hash": "B66F90970DC7BB28D49DB459C15CF06CCDB48950"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755501,
        "time": "2018-02-15T15:57:18.088-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "9E914995D00895504D6DEB850AEEEAA5D8BDCFF1",
          "parts": {
            "total": 1,
            "hash": "0D255F0F6134454C3DBB577C2D0AC0F682ECF596"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "B548C63A5583F50A58B6B8D198B5D131BBDFBFDE",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "91B7904E69C6032104BCF53D89D6CC3C30621D24",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "9E914995D00895504D6DEB850AEEEAA5D8BDCFF1",
        "parts": {
          "total": 1,
          "hash": "0D255F0F6134454C3DBB577C2D0AC0F682ECF596"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755500,
        "time": "2018-02-15T15:57:16.41-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "58B1B5B6A38C875EA1037C76C1C17FB2DEE68B45",
          "parts": {
            "total": 1,
            "hash": "51CCC716A6BB7BCA65FC72CB0190B4A3CC6F4E42"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "14E3F756AF762551F943A48AA91D9986133E2DC5",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "16485AA607B8C8553B0B789FE3C978C4AA37B171",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "58B1B5B6A38C875EA1037C76C1C17FB2DEE68B45",
        "parts": {
          "total": 1,
          "hash": "51CCC716A6BB7BCA65FC72CB0190B4A3CC6F4E42"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755499,
        "time": "2018-02-15T15:57:14.659-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "665B6DA9881751A488C738093D9A2BF34B92F097",
          "parts": {
            "total": 1,
            "hash": "71E9D6ECF456E08FFE97D9DF9BC932182361CE95"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "1CB85053676BAC6336E2230318352F9A34A3FFBC",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "97B359797B6D4E47108033D573CCA65512E981E1",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "665B6DA9881751A488C738093D9A2BF34B92F097",
        "parts": {
          "total": 1,
          "hash": "71E9D6ECF456E08FFE97D9DF9BC932182361CE95"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755498,
        "time": "2018-02-15T15:57:12.833-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "832290E239F37BB2648CF7F8B4E0823DD4DA20BB",
          "parts": {
            "total": 1,
            "hash": "D11104B9361ADBD43C7B5CA212B78CBB8ABBD43A"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "E23613230FF3269D9763D1B1931D13D9CA1BE3D2",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "6D0BC35C38A5548AB626DE67C76A506A6F9F36BC",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "832290E239F37BB2648CF7F8B4E0823DD4DA20BB",
        "parts": {
          "total": 1,
          "hash": "D11104B9361ADBD43C7B5CA212B78CBB8ABBD43A"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1755497,
        "time": "2018-02-15T15:57:07.501-05:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "2BDA489C4216C02CC4DDFA9B2B14AF1E1A9F95EA",
          "parts": {
            "total": 1,
            "hash": "F0E78E7A053BBA96CCEB72210C7916D3A7C7A64B"
          }
        },
        "total_txs": 1080,
        "last_commit_hash": "11B7266F764E1AA7DC243A06325270F7B430543C",
        "data_hash": "",
        "validators_hash": "297FD3ED8A1C7A7B3209B6F1A1B264FAD072270C",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "0E33476211F538F0B3D8111DB10FE73FE8F6985C",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    }
  ]
}
        



## /status

### Query Status [GET]
is to query block chain status


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "node_info": {
    "pub_key": "96F0B9C94AA8E1EF5462A3E59BE780D34C454603B118C027DA38416402325CB6",
    "moniker": "95.85.37.158",
    "network": "gaia-2",
    "remote_addr": "",
    "listen_addr": "95.85.37.158:46656",
    "version": "0.15.0-381fe19",
    "other": [
      "wire_version=0.7.2",
      "p2p_version=0.5.0",
      "consensus_version=v1/0.2.2",
      "rpc_version=0.7.0/3",
      "tx_index=on",
      "rpc_addr=tcp://0.0.0.0:46657"
    ]
  },
  "pub_key": {
    "type": "ed25519",
    "data": "2B26539CFA678ED5AAA72C55FB6DD4B394D160DDC0478DC50654658683F53A9B"
  },
  "latest_block_hash": "CA6784C6B8B64041843593A21C4E4F0CF857FBC2",
  "latest_app_hash": "2AEE1A9DF0CB0A539253FCD291E2AE9B09285D26",
  "latest_block_height": 1755517,
  "latest_block_time": "2018-02-15T15:58:17.375-05:00",
  "syncing": false
}
        



## /tx/decode

### Decode Raw [POST]
is to decode tx string


+ Request 



    + Body

            FgMBBmdhaWEtMgAAAAAAAAAAaQAAAAIBAQABBHNpZ3MBFHM0pLJmjeHO8N19umlcKUSew6DQIAEBAAEEc2lncwEUczSksmaN4c7w3X26aVwpRJ7DoNABAQEHZmVybWlvbgAAAAAAAAABAQEAAQRzaWdzARRqmuoDMVmHmdXwCeybfWNbuPNO/wEBAQdmZXJtaW9uAAAAAAAAAAEB5pH7Kschidpq7JobqzmfyiiVaYBT7JBXleIDrF6kbIwjoJzFv6zhuumL1G2yBNFN1ecjuKixcrNYeNTH3epODQFDGBaojUlBJwZnojLRIJGmwWB92kp+Vm9HD+2dU9xwGw==        

+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "type": "sigs/one",
  "data": {
    "tx": {
      "type": "chain/tx",
      "data": {
        "chain_id": "gaia-2",
        "expires_at": 0,
        "tx": {
          "type": "nonce",
          "data": {
            "sequence": 2,
            "signers": [
              {
                "chain": "",
                "app": "sigs",
                "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
              }
            ],
            "tx": {
              "type": "coin/send",
              "data": {
                "inputs": [
                  {
                    "address": {
                      "chain": "",
                      "app": "sigs",
                      "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
                    },
                    "coins": [
                      {
                        "denom": "fermion",
                        "amount": 1
                      }
                    ]
                  }
                ],
                "outputs": [
                  {
                    "address": {
                      "chain": "",
                      "app": "sigs",
                      "addr": "6A9AEA0331598799D5F009EC9B7D635BB8F34EFF"
                    },
                    "coins": [
                      {
                        "denom": "fermion",
                        "amount": 1
                      }
                    ]
                  }
                ]
              }
            }
          }
        }
      }
    },
    "signature": {
      "Sig": {
        "type": "ed25519",
        "data": "E691FB2AC72189DA6AEC9A1BAB399FCA2895698053EC905795E203AC5EA46C8C23A09CC5BFACE1BAE98BD46DB204D14DD5E723B8A8B172B35878D4C7DDEA4E0D"
      },
      "Pubkey": {
        "type": "ed25519",
        "data": "431816A88D4941270667A232D12091A6C1607DDA4A7E566F470FED9D53DC701B"
      }
    }
  }
}
        



## /tx/{txhash}

+ Parameters
    + txhash: `640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C` (string)

### Query Tx [GET]
is to query "inner" transaction by txhash


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "height": 10546,
  "tx": {
    "type": "coin/send",
    "data": {
      "inputs": [
        {
          "address": {
            "chain": "",
            "app": "sigs",
            "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
          },
          "coins": [
            {
              "denom": "fermion",
              "amount": 10
            }
          ]
        }
      ],
      "outputs": [
        {
          "address": {
            "chain": "",
            "app": "sigs",
            "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
          },
          "coins": [
            {
              "denom": "fermion",
              "amount": 10
            }
          ]
        }
      ]
    }
  },
  "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
}
        



## /tx/{txhash}/raw

+ Parameters
    + txhash: `640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C` (string)

### Query Raw Tx [GET]
is to query a raw transaction by txhash


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "height": 10546,
  "tx": {
    "type": "sigs/one",
    "data": {
      "tx": {
        "type": "chain/tx",
        "data": {
          "chain_id": "gaia-2",
          "expires_at": 0,
          "tx": {
            "type": "nonce",
            "data": {
              "sequence": 7,
              "signers": [
                {
                  "chain": "",
                  "app": "sigs",
                  "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
                }
              ],
              "tx": {
                "type": "coin/send",
                "data": {
                  "inputs": [
                    {
                      "address": {
                        "chain": "",
                        "app": "sigs",
                        "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
                      },
                      "coins": [
                        {
                          "denom": "fermion",
                          "amount": 10
                        }
                      ]
                    }
                  ],
                  "outputs": [
                    {
                      "address": {
                        "chain": "",
                        "app": "sigs",
                        "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
                      },
                      "coins": [
                        {
                          "denom": "fermion",
                          "amount": 10
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "signature": {
        "Sig": {
          "type": "ed25519",
          "data": "F669F163CA7BAD8E564063F57520906C1510256416B6D0A28421CD401E071FF4A3FFC8C83C37760BE6CFD252D28940926709C723DD010E549953E3005FF91808"
        },
        "Pubkey": {
          "type": "ed25519",
          "data": "686A00033798FFA14B00C1B207C3DADF42AD122FA5F9C9D4A9BEEDB827EA9994"
        }
      }
    }
  },
  "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
}
        



## /txs/recentcoin{?limit}

+ Parameters
    + limit: `2` (number)

### Query Recent Coin Tx [GET]
is to get recent coin transactions


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "tx_hash": "A52A5E2804267D6F03519762CFB77F8A5CD1CCC1",
    "time": "2018-02-04T18:00:50.371+08:00",
    "height": 1446819,
    "from": "F75D0FD7036A3BB9092DD0938BBF0A9323224832",
    "to": "ADFFC348E9574B3CAC19AE16C27C90942C5D4E12"
  },
  {
    "tx_hash": "5742F4C4C12AD561936DAA52C17D07EE04CD71AE",
    "time": "2018-02-04T17:09:19.974+08:00",
    "height": 1446767,
    "from": "ADFFC348E9574B3CAC19AE16C27C90942C5D4E12",
    "to": "17E5DF33EFFCF474AFBBDB345AFBDEFEF8E6EBFE"
  }
]
        



## /txs/recentstake{?limit}

+ Parameters
    + limit: `2` (number)

### Query Recent Stake Tx [GET]
is to get recent stake transactions


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "tx_hash": "82D5DEC9CE790C74014AC9156E80D89D3D0F7CA5",
    "time": "2018-02-04T18:00:50.371+08:00",
    "height": 1446819,
    "from": "17E5DF33EFFCF474AFBBDB345AFBDEFEF8E6EBFE",
    "type": "delegate",
    "amount": {
      "denom": "fermion",
      "amount": 9
    }
  },
  {
    "tx_hash": "3DDD79DDEBD77CCDB57D091083B1A5D4C0EAB554",
    "time": "2018-02-04T18:00:50.371+08:00",
    "height": 1446819,
    "from": "ADFFC348E9574B3CAC19AE16C27C90942C5D4E12",
    "type": "delegate",
    "amount": {
      "denom": "fermion",
      "amount": 1
    }
  }
]
        



## /validators/{height}

+ Parameters
    + height: `10546` (number)

### Query Validators [GET]
is to query validators by height


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "block_height": 10546,
  "validators": [
    {
      "address": "3294678052AAD1648F6E0AFBCECE3BD09B402CB1",
      "pub_key": {
        "type": "ed25519",
        "data": "7A1C7CD300A797A80479FC7C717C8CEB467976775044BAFFE630DADB01F4F4D9"
      },
      "voting_power": 1000,
      "accum": -6000
    },
    {
      "address": "600AD8E3023710167C242AD1D26C4FB7AD3A3A39",
      "pub_key": {
        "type": "ed25519",
        "data": "1320BC3E22BCFDD2F9B133EBBA8BC393F9160E54917962D6E75245D885EAAD14"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "898766AF03F350D117657A7E44E54D92423F9E83",
      "pub_key": {
        "type": "ed25519",
        "data": "492DCDE8F3394A97BB92ECC3D025CEA5E380C7A04BF30991FDAF262EECC672C6"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "CA956F20A083A26BF5B9C766E95D246E0624EDC6",
      "pub_key": {
        "type": "ed25519",
        "data": "845F2C16B97D71FAF7C32724DF01A09120E4680FACFF0657977ACC852DF5E7C6"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "DC321F5C8DD94234903B53D44C1CF3B37B817950",
      "pub_key": {
        "type": "ed25519",
        "data": "0A29EF59C9B01CFC880354F83D1253FDF04B9FDCD7411B96D801B52C6F03D376"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "DD59852B326AB9AC57E3A8CAF4F00459A9539970",
      "pub_key": {
        "type": "ed25519",
        "data": "2B26539CFA678ED5AAA72C55FB6DD4B394D160DDC0478DC50654658683F53A9B"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "E99FA5A12168E0C4194F1324866164331A1AC2C0",
      "pub_key": {
        "type": "ed25519",
        "data": "27D710DD0FF5276651865FA6EB9B4804E46F987D1BA6A901AC35E2C0D48D7664"
      },
      "voting_power": 1000,
      "accum": 1000
    }
  ]
}
        


