
# Group Handlers

## /account/{address}

+ Parameters
    + address: `7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0` (string)

### Query Account [GET]
is to query an account by address


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "height": 1036676,
  "data": {
    "coins": [
      {
        "denom": "fermion",
        "amount": 4
      }
    ],
    "credit": []
  }
}
        



## /account/{address}/tx/coin

+ Parameters
    + address: `7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0` (string)

### Search Coin Tx By Account [GET]
is to search for
all SendTx transactions with this account as sender
or receiver


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "height": 178507,
    "tx": {
      "type": "fee/tx",
      "data": {
        "fee": {
          "denom": "fermion",
          "amount": 1
        },
        "payer": {
          "chain": "",
          "app": "sigs",
          "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
        },
        "tx": {
          "type": "coin/send",
          "data": {
            "inputs": [
              {
                "address": {
                  "chain": "",
                  "app": "sigs",
                  "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
                },
                "coins": [
                  {
                    "denom": "fermion",
                    "amount": 2
                  }
                ]
              }
            ],
            "outputs": [
              {
                "address": {
                  "chain": "",
                  "app": "sigs",
                  "addr": "6A9AEA0331598799D5F009EC9B7D635BB8F34EFF"
                },
                "coins": [
                  {
                    "denom": "fermion",
                    "amount": 2
                  }
                ]
              }
            ]
          }
        }
      }
    },
    "txhash": "83527AC99E577CEF7408FA8BD2F660F7D95C69BC"
  },
  {
    "height": 178071,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 1
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "6A9AEA0331598799D5F009EC9B7D635BB8F34EFF"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 1
              }
            ]
          }
        ]
      }
    },
    "txhash": "9C62C9AB93664ECB7162683537CF9C028EF8C262"
  },
  {
    "height": 66804,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 2
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "D3EEBDF9593BE3D3C0B249DB56A9E45DC490FE97"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 2
              }
            ]
          }
        ]
      }
    },
    "txhash": "76E8027FD93F83892A3204B01CCE0FC6FED3563D"
  },
  {
    "height": 10546,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ]
      }
    },
    "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
  }
]
        



## /block/{height}

+ Parameters
    + height: `10546` (number)

### Query Block [GET]
is to query a block by height


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "block_meta": {
    "block_id": {
      "hash": "F78FF304909587F77A52D5900367783F69A4FAAD",
      "parts": {
        "total": 1,
        "hash": "5DCA1BA2A87A084EB1CEFA7D145BEAA4A027C320"
      }
    },
    "header": {
      "chain_id": "gaia-2",
      "height": 10546,
      "time": "2018-01-07T00:53:54.522+08:00",
      "num_txs": 1,
      "last_block_id": {
        "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
        "parts": {
          "total": 1,
          "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
        }
      },
      "total_txs": 10,
      "last_commit_hash": "1952C539B87606ADF893DD8A87002A0681946597",
      "data_hash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C",
      "validators_hash": "EE5F3404034C524501629B56E0DDC38FAD651F04",
      "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
      "app_hash": "FB3044CF1112AB6D8CA02FE712848A7BF990DB4A",
      "last_results_hash": "",
      "evidence_hash": ""
    }
  },
  "block": {
    "header": {
      "chain_id": "gaia-2",
      "height": 10546,
      "time": "2018-01-07T00:53:54.522+08:00",
      "num_txs": 1,
      "last_block_id": {
        "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
        "parts": {
          "total": 1,
          "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
        }
      },
      "total_txs": 10,
      "last_commit_hash": "1952C539B87606ADF893DD8A87002A0681946597",
      "data_hash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C",
      "validators_hash": "EE5F3404034C524501629B56E0DDC38FAD651F04",
      "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
      "app_hash": "FB3044CF1112AB6D8CA02FE712848A7BF990DB4A",
      "last_results_hash": "",
      "evidence_hash": ""
    },
    "data": {
      "txs": [
        "FgMBBmdhaWEtMgAAAAAAAAAAaQAAAAcBAQABBHNpZ3MBFPddD9cDaju5CS3Qk4u/CpMjIkgyIAEBAAEEc2lncwEU910P1wNqO7kJLdCTi78KkyMiSDIBAQEHZmVybWlvbgAAAAAAAAAKAQEAAQRzaWdzARRzNKSyZo3hzvDdfbppXClEnsOg0AEBAQdmZXJtaW9uAAAAAAAAAAoB9mnxY8p7rY5WQGP1dSCQbBUQJWQWttCihCHNQB4HH/Sj/8jIPDd2C+bP0lLSiUCSZwnHI90BDlSZU+MAX/kYCAFoagADN5j/oUsAwbIHw9rfQq0SL6X5ydSpvu24J+qZlA=="
      ]
    },
    "evidence": {
      "evidence": []
    },
    "last_commit": {
      "blockID": {
        "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
        "parts": {
          "total": 1,
          "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
        }
      },
      "precommits": [
        {
          "validator_address": "3294678052AAD1648F6E0AFBCECE3BD09B402CB1",
          "validator_index": 0,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.084+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "3FC160B1DC1FEC8518F8272D10BDBE898A1AC2CEDDB7ADC699B5781D943BFA97FCCBB98196F54C1A3A6A22DB2130E88D547794EA376609A27E9E5BAB7931D106"
          }
        },
        {
          "validator_address": "600AD8E3023710167C242AD1D26C4FB7AD3A3A39",
          "validator_index": 1,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.025+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "C767A4DAEE0BE3B69D8F4288C39D2EF1A96893B32DFAFBFA762F5E755A7E4E94324F7D97D2FB67FF3BAF8BB700D3959C0805816A1ECDC87CF83B2C565CF82302"
          }
        },
        {
          "validator_address": "898766AF03F350D117657A7E44E54D92423F9E83",
          "validator_index": 2,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.072+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "6D88CA3FD8FFB12A548B47492296D2966E6E011285FC5342C73401A05FBD7EB5CBF9D86FA75BE0E9E0AB91CC624FA36838C1DA57B3848CDA47FB9836A4AC2E00"
          }
        },
        {
          "validator_address": "CA956F20A083A26BF5B9C766E95D246E0624EDC6",
          "validator_index": 3,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.003+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "0F8DE68BFBE6D2CF4F736111BAD526B5F68836A0E57F7E802E51548937A7F703405C43CCF69A3CEB27271DCA459CA9A0CCF3507A017C7BC6A39C98E1A175A806"
          }
        },
        {
          "validator_address": "DC321F5C8DD94234903B53D44C1CF3B37B817950",
          "validator_index": 4,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.024+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "B96A4F40BEDC0083C41CD3670D31B8BE13C74DD2D60B829D4D09DF4B274A30BE2FD4DACA1F1FC6A813D9B9F9F76623AD071A1BBD53B374BA9A283F57AFCDDE05"
          }
        },
        {
          "validator_address": "DD59852B326AB9AC57E3A8CAF4F00459A9539970",
          "validator_index": 5,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.106+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "DD9780B51D0404D89ADE2340967069309FE776FDD7DBF063870FDCABF440E0F2A56D5EBEC5DD1327A5C55286BB86353CA4B6A01821B95E3ED30E42748BDF6C0E"
          }
        },
        {
          "validator_address": "E99FA5A12168E0C4194F1324866164331A1AC2C0",
          "validator_index": 6,
          "height": 10545,
          "round": 0,
          "timestamp": "2018-01-07T00:53:36.065+08:00",
          "type": 2,
          "block_id": {
            "hash": "AF9F37540EEB70F4116F6EF27072487110AC8D54",
            "parts": {
              "total": 1,
              "hash": "D605DC97C630595FE1467682F8D2DFB157CE7305"
            }
          },
          "signature": {
            "type": "ed25519",
            "data": "71ED7A8A7A2D820D46D45435AB3EEBE8CCA5EE5E82DFC8770BE3A2FE00A2FAF54F19143831C3F4364C68BB68FAD72CC6C09418D5828EDAC22BAF4DA42C1FC701"
          }
        }
      ]
    }
  }
}
        



## /block/{height}/tx

+ Parameters
    + height: `10546` (number)

### Search Tx By Block [GET]
is to search for inner transaction by block height


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "height": 10546,
    "tx": {
      "type": "coin/send",
      "data": {
        "inputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ],
        "outputs": [
          {
            "address": {
              "chain": "",
              "app": "sigs",
              "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
            },
            "coins": [
              {
                "denom": "fermion",
                "amount": 10
              }
            ]
          }
        ]
      }
    },
    "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
  }
]
        



## /blocks/recent

### Query Recent Blocks [GET]
is to query recent 20 blocks


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "last_height": 1036677,
  "block_metas": [
    {
      "block_id": {
        "hash": "73DABBD9D0BFF35B503EAA87EA89E231D58BA57A",
        "parts": {
          "total": 1,
          "hash": "7261B3DAE6BDBEE5E9A98A4D3B9AA91CBB4966D8"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036677,
        "time": "2018-01-26T16:13:16.308+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "CFA9D04B6C585E5311D9D8CE405CAC12531C4F16",
          "parts": {
            "total": 1,
            "hash": "71ABF773F3807DBB88A6C5A40404269647CE434D"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "80C162942FAE65F31AA6881532521CA48D44846D",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "62D1CAECDBEA1270CA07422F02F130B79640CC29",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "CFA9D04B6C585E5311D9D8CE405CAC12531C4F16",
        "parts": {
          "total": 1,
          "hash": "71ABF773F3807DBB88A6C5A40404269647CE434D"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036676,
        "time": "2018-01-26T16:13:14.752+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "82EBE97DA146CE9ECD2EE99A6C062DC19318014F",
          "parts": {
            "total": 1,
            "hash": "0A0AF8E5F93F29DCC8AA2C391938301FA8FB9769"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "DFD523E212D3E4C7AAED5A899880A76925EE27A7",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "7DE3F91418B8C023AD10B5F462EF81944578907C",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "82EBE97DA146CE9ECD2EE99A6C062DC19318014F",
        "parts": {
          "total": 1,
          "hash": "0A0AF8E5F93F29DCC8AA2C391938301FA8FB9769"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036675,
        "time": "2018-01-26T16:13:13.184+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "59784444D64FE5D21FBBAB248035025DE7A8A280",
          "parts": {
            "total": 1,
            "hash": "F08D75A12B9A20B5149014F350438C6E0A357CEB"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "905927563D3229FB7B62AE7E014EBCB3878EF671",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "1F3D3B6801C0476304926539645C8AFA13673ADE",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "59784444D64FE5D21FBBAB248035025DE7A8A280",
        "parts": {
          "total": 1,
          "hash": "F08D75A12B9A20B5149014F350438C6E0A357CEB"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036674,
        "time": "2018-01-26T16:13:11.656+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "938681C02AE50CA32A17DB884C948232B375B8F8",
          "parts": {
            "total": 1,
            "hash": "3CFCC2B913CCB233219E9D60A89EF7D32A43574B"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "322F88D4E9CAED294B8033AAD70D2D6279F2E199",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "2D9F69576023B1E1E3A672ED0E44230F437CDE27",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "938681C02AE50CA32A17DB884C948232B375B8F8",
        "parts": {
          "total": 1,
          "hash": "3CFCC2B913CCB233219E9D60A89EF7D32A43574B"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036673,
        "time": "2018-01-26T16:13:10.085+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "34AA146827D5A3FF8B040ADF29F5DFA616666191",
          "parts": {
            "total": 1,
            "hash": "8F624A700E93EAADCA4AA80FEEE6927B06CA1039"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "70BE99E01492D0484759BFC89EA80AC27DBD7366",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "8187FBAE9251BC4729137CF17684B119FF97D0B8",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "34AA146827D5A3FF8B040ADF29F5DFA616666191",
        "parts": {
          "total": 1,
          "hash": "8F624A700E93EAADCA4AA80FEEE6927B06CA1039"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036672,
        "time": "2018-01-26T16:13:08.485+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "E6FF6BEB4AC629E4240646710E4F74C27664C88A",
          "parts": {
            "total": 1,
            "hash": "FC61AF795481722BCB9D287F31D0F5B194180BD3"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "95E178DD4200D4132DCE4C13195F7DA45E6653A6",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "76F75FE3D290170B158F9D89445E5022820BFBD2",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "E6FF6BEB4AC629E4240646710E4F74C27664C88A",
        "parts": {
          "total": 1,
          "hash": "FC61AF795481722BCB9D287F31D0F5B194180BD3"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036671,
        "time": "2018-01-26T16:13:06.887+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "52EE43418EFD99180BD00CE6A3071C31D21B43EA",
          "parts": {
            "total": 1,
            "hash": "E8AB3DF07071C323EFBC7A353DF5511216B7D5BF"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "F27B4BCC27B5C217E192AA1F70EEC8289136678F",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "8A1F3B750620F65F6A7A5006C912CB7888D3C910",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "52EE43418EFD99180BD00CE6A3071C31D21B43EA",
        "parts": {
          "total": 1,
          "hash": "E8AB3DF07071C323EFBC7A353DF5511216B7D5BF"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036670,
        "time": "2018-01-26T16:13:05.321+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "974165423DB96C9F0126F73DE85C7440EDCE4818",
          "parts": {
            "total": 1,
            "hash": "46B7A4400019F5373728118A8EFD0AEDC5C3591F"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "5ED20CC6FBC4206B87AE503A58F595A3A998A0B7",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "F02CFA7A2BD5F34D4CE943675001D9999536154C",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "974165423DB96C9F0126F73DE85C7440EDCE4818",
        "parts": {
          "total": 1,
          "hash": "46B7A4400019F5373728118A8EFD0AEDC5C3591F"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036669,
        "time": "2018-01-26T16:13:03.776+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "F79D015D9238747CDD6CDC9EBBB1CA13CB38AA50",
          "parts": {
            "total": 1,
            "hash": "B9DBB6648BD1E1C1AD831FCDE41854BBC4184E0A"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "D379CCCA5D3C0E69AEDF848A8365B6C5DDB16446",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "E106136C4F972DB7E44721978FB31AE871E66547",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "F79D015D9238747CDD6CDC9EBBB1CA13CB38AA50",
        "parts": {
          "total": 1,
          "hash": "B9DBB6648BD1E1C1AD831FCDE41854BBC4184E0A"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036668,
        "time": "2018-01-26T16:13:02.182+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "E995327D9E36914DE48A585EA1A6015D3C217455",
          "parts": {
            "total": 1,
            "hash": "298BA17FB64BB926DDCD6D3C1B320A4A6C1A17FF"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "F87A943B393BCF784984BB51D93A000458E4DF37",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "971599988925E1E21F6AFF6F20E67C716015C3CB",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "E995327D9E36914DE48A585EA1A6015D3C217455",
        "parts": {
          "total": 1,
          "hash": "298BA17FB64BB926DDCD6D3C1B320A4A6C1A17FF"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036667,
        "time": "2018-01-26T16:13:00.505+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "A901D9991EA67E0B236171C61E286C02A4BEF37E",
          "parts": {
            "total": 1,
            "hash": "BE49EA437BD5715BE23E1CA89FACC8267885394D"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "1419C290C82000C806F87060E17E4DC5706F55B0",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "9894CD68E2A8846286475463B9A19E79EEB097D0",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "A901D9991EA67E0B236171C61E286C02A4BEF37E",
        "parts": {
          "total": 1,
          "hash": "BE49EA437BD5715BE23E1CA89FACC8267885394D"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036666,
        "time": "2018-01-26T16:12:55.524+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "11721BBBDC8F392560D93F019789579DB5DC25A7",
          "parts": {
            "total": 1,
            "hash": "323F6DA07B4ADF5662D406978532090DCDE44BAF"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "3BB1F861CB582A704E42EA4DF247A58228E19E47",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "FDBAF6EB4287AEE62E20B4E0639291AC023AD0E6",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "11721BBBDC8F392560D93F019789579DB5DC25A7",
        "parts": {
          "total": 1,
          "hash": "323F6DA07B4ADF5662D406978532090DCDE44BAF"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036665,
        "time": "2018-01-26T16:12:53.992+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "9043DA547AEBEA593E24664D62CA0CA02AFACC3E",
          "parts": {
            "total": 1,
            "hash": "0A0DB1CC663DF6E48492CC7197A052932E360A4B"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "9D065FA179D4D35308C2CF623414DE97AB44AEA9",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "E31E41F2D98455DC8A0202A413D6BE52AA31F689",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "9043DA547AEBEA593E24664D62CA0CA02AFACC3E",
        "parts": {
          "total": 1,
          "hash": "0A0DB1CC663DF6E48492CC7197A052932E360A4B"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036664,
        "time": "2018-01-26T16:12:52.438+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "16A27698C98845A21BFE32A65326FAAD0A7255DB",
          "parts": {
            "total": 1,
            "hash": "E1D7E0E99A4B8D354E3E0884E635F93C2C5595F9"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "0284280F91DD0214C4979EB68FD7C0EE32EEB661",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "AFD00E53AF3C586D3BA431D6A034CFF913A74CED",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "16A27698C98845A21BFE32A65326FAAD0A7255DB",
        "parts": {
          "total": 1,
          "hash": "E1D7E0E99A4B8D354E3E0884E635F93C2C5595F9"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036663,
        "time": "2018-01-26T16:12:50.892+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "712F836FF0AE91467B864596E9429E97DA01A879",
          "parts": {
            "total": 1,
            "hash": "77D338E795317449AB2999FA6F9F2041BEDA67AE"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "667C21792E8DE1155F01F0DC3F6E674D54B4C563",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "0D5AFAAE883C51E30C577B070642D20687D99454",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "712F836FF0AE91467B864596E9429E97DA01A879",
        "parts": {
          "total": 1,
          "hash": "77D338E795317449AB2999FA6F9F2041BEDA67AE"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036662,
        "time": "2018-01-26T16:12:49.318+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "32B7BD26BBFC5650DE1944D06203C761E2831FCD",
          "parts": {
            "total": 1,
            "hash": "28D70587E64C5DB7019D334C2747D5FD1E3ECB6F"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "BFBAE964E91DAAA5FBA10DF98ED823B3B7403780",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "B515DCBBDE11A43AEB50D8E051724933436C1951",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "32B7BD26BBFC5650DE1944D06203C761E2831FCD",
        "parts": {
          "total": 1,
          "hash": "28D70587E64C5DB7019D334C2747D5FD1E3ECB6F"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036661,
        "time": "2018-01-26T16:12:47.722+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "7B88F20AC294A69ADE7B7905ECA7AADD504250F6",
          "parts": {
            "total": 1,
            "hash": "C14E6F74043352F4E982273AE993F64EDF2E7936"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "9F747ED2AC6C83D8E43D5C66755971E246300DDF",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "1BAD3C624E9F8E1A93A6E53CA02C6BE062A54EC8",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "7B88F20AC294A69ADE7B7905ECA7AADD504250F6",
        "parts": {
          "total": 1,
          "hash": "C14E6F74043352F4E982273AE993F64EDF2E7936"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036660,
        "time": "2018-01-26T16:12:46.159+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "2CEA9D505553A390765FF05C4F581E8E873DE3C9",
          "parts": {
            "total": 1,
            "hash": "5D12861247FC5C724AAFA8CC320A7D42F4060D0C"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "3CCABE993059468756895803FC18CF6A9C999392",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "11ECECBBC30F9F63F02B201C08ABE24E654EC08B",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "2CEA9D505553A390765FF05C4F581E8E873DE3C9",
        "parts": {
          "total": 1,
          "hash": "5D12861247FC5C724AAFA8CC320A7D42F4060D0C"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036659,
        "time": "2018-01-26T16:12:44.596+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "57B82BD37A7824540BCBBBF71B6015A586756C79",
          "parts": {
            "total": 1,
            "hash": "7CFDE6C2A9BD962C141AF47BF5E97A86F1CF0D96"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "6BCF0A82EB306E3D7CBF754DF67790FEDC793408",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "2B03FA3EF06705F71009351E92BDA09AF1E32392",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "57B82BD37A7824540BCBBBF71B6015A586756C79",
        "parts": {
          "total": 1,
          "hash": "7CFDE6C2A9BD962C141AF47BF5E97A86F1CF0D96"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036658,
        "time": "2018-01-26T16:12:43.022+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "519442C3A1D2FAE0A0FD7148204A7ED6FEFFAAD9",
          "parts": {
            "total": 1,
            "hash": "B79C0AF8996C439D1F8C5A331C04C69D47E9E959"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "EB30D315ED02C99409CF384DED885B11AC97B6B6",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "7D7B78D81C8C4F5D7C489BB29BA0D2AE9EA58ED9",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    },
    {
      "block_id": {
        "hash": "519442C3A1D2FAE0A0FD7148204A7ED6FEFFAAD9",
        "parts": {
          "total": 1,
          "hash": "B79C0AF8996C439D1F8C5A331C04C69D47E9E959"
        }
      },
      "header": {
        "chain_id": "gaia-2",
        "height": 1036657,
        "time": "2018-01-26T16:12:41.47+08:00",
        "num_txs": 0,
        "last_block_id": {
          "hash": "7CBD7B0D59AF72E004D1DED3CD64A46ED38F9DFB",
          "parts": {
            "total": 1,
            "hash": "1D4F71C47F47CBD08E7F1EFEB9DA74E36D27D39F"
          }
        },
        "total_txs": 284,
        "last_commit_hash": "D71EBF22693EB6C840C15F61FB268AFCC3C3C5F6",
        "data_hash": "",
        "validators_hash": "51D9D33D0149DD6431BDC9D08A328062AB54082A",
        "consensus_hash": "B9FD9BB442BAD53793C4C744D44B5F8AF4C09438",
        "app_hash": "0494E416DDAA470A7FBD00085F57D9C05691C863",
        "last_results_hash": "",
        "evidence_hash": ""
      }
    }
  ]
}
        



## /status

### Query Status [GET]
is to query block chain status


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "node_info": {
    "pub_key": "14E9F1A5C0CE3C93961249E2DC97C6DF011E945CB5C3B7D888064C9A76C122C4",
    "moniker": "159.89.198.221",
    "network": "gaia-2",
    "remote_addr": "",
    "listen_addr": "192.168.0.104:46656",
    "version": "0.15.0",
    "other": [
      "wire_version=0.7.2",
      "p2p_version=0.5.0",
      "consensus_version=v1/0.2.2",
      "rpc_version=0.7.0/3",
      "tx_index=on",
      "rpc_addr=tcp://0.0.0.0:46657"
    ]
  },
  "pub_key": {
    "type": "ed25519",
    "data": "72B9C2BFEF5977F934D32A810532318228CA28FBF671058637A0B5FDFC2079E3"
  },
  "latest_block_hash": "73DABBD9D0BFF35B503EAA87EA89E231D58BA57A",
  "latest_app_hash": "62D1CAECDBEA1270CA07422F02F130B79640CC29",
  "latest_block_height": 1036677,
  "latest_block_time": "2018-01-26T16:13:16.308+08:00",
  "syncing": false
}
        



## /tx/decode

### Decode Raw [POST]
is to decode tx string


+ Request 



    + Body

            FgMBBmdhaWEtMgAAAAAAAAAAaQAAAAIBAQABBHNpZ3MBFHM0pLJmjeHO8N19umlcKUSew6DQIAEBAAEEc2lncwEUczSksmaN4c7w3X26aVwpRJ7DoNABAQEHZmVybWlvbgAAAAAAAAABAQEAAQRzaWdzARRqmuoDMVmHmdXwCeybfWNbuPNO/wEBAQdmZXJtaW9uAAAAAAAAAAEB5pH7Kschidpq7JobqzmfyiiVaYBT7JBXleIDrF6kbIwjoJzFv6zhuumL1G2yBNFN1ecjuKixcrNYeNTH3epODQFDGBaojUlBJwZnojLRIJGmwWB92kp+Vm9HD+2dU9xwGw==        

+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "type": "sigs/one",
  "data": {
    "tx": {
      "type": "chain/tx",
      "data": {
        "chain_id": "gaia-2",
        "expires_at": 0,
        "tx": {
          "type": "nonce",
          "data": {
            "sequence": 2,
            "signers": [
              {
                "chain": "",
                "app": "sigs",
                "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
              }
            ],
            "tx": {
              "type": "coin/send",
              "data": {
                "inputs": [
                  {
                    "address": {
                      "chain": "",
                      "app": "sigs",
                      "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
                    },
                    "coins": [
                      {
                        "denom": "fermion",
                        "amount": 1
                      }
                    ]
                  }
                ],
                "outputs": [
                  {
                    "address": {
                      "chain": "",
                      "app": "sigs",
                      "addr": "6A9AEA0331598799D5F009EC9B7D635BB8F34EFF"
                    },
                    "coins": [
                      {
                        "denom": "fermion",
                        "amount": 1
                      }
                    ]
                  }
                ]
              }
            }
          }
        }
      }
    },
    "signature": {
      "Sig": {
        "type": "ed25519",
        "data": "E691FB2AC72189DA6AEC9A1BAB399FCA2895698053EC905795E203AC5EA46C8C23A09CC5BFACE1BAE98BD46DB204D14DD5E723B8A8B172B35878D4C7DDEA4E0D"
      },
      "Pubkey": {
        "type": "ed25519",
        "data": "431816A88D4941270667A232D12091A6C1607DDA4A7E566F470FED9D53DC701B"
      }
    }
  }
}
        



## /tx/{txhash}

+ Parameters
    + txhash: `640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C` (string)

### Query Tx [GET]
is to query "inner" transaction by txhash


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "height": 10546,
  "tx": {
    "type": "coin/send",
    "data": {
      "inputs": [
        {
          "address": {
            "chain": "",
            "app": "sigs",
            "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
          },
          "coins": [
            {
              "denom": "fermion",
              "amount": 10
            }
          ]
        }
      ],
      "outputs": [
        {
          "address": {
            "chain": "",
            "app": "sigs",
            "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
          },
          "coins": [
            {
              "denom": "fermion",
              "amount": 10
            }
          ]
        }
      ]
    }
  },
  "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
}
        



## /tx/{txhash}/raw

+ Parameters
    + txhash: `640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C` (string)

### Query Raw Tx [GET]
is to query a raw transaction by txhash


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "height": 10546,
  "tx": {
    "type": "sigs/one",
    "data": {
      "tx": {
        "type": "chain/tx",
        "data": {
          "chain_id": "gaia-2",
          "expires_at": 0,
          "tx": {
            "type": "nonce",
            "data": {
              "sequence": 7,
              "signers": [
                {
                  "chain": "",
                  "app": "sigs",
                  "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
                }
              ],
              "tx": {
                "type": "coin/send",
                "data": {
                  "inputs": [
                    {
                      "address": {
                        "chain": "",
                        "app": "sigs",
                        "addr": "F75D0FD7036A3BB9092DD0938BBF0A9323224832"
                      },
                      "coins": [
                        {
                          "denom": "fermion",
                          "amount": 10
                        }
                      ]
                    }
                  ],
                  "outputs": [
                    {
                      "address": {
                        "chain": "",
                        "app": "sigs",
                        "addr": "7334A4B2668DE1CEF0DD7DBA695C29449EC3A0D0"
                      },
                      "coins": [
                        {
                          "denom": "fermion",
                          "amount": 10
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "signature": {
        "Sig": {
          "type": "ed25519",
          "data": "F669F163CA7BAD8E564063F57520906C1510256416B6D0A28421CD401E071FF4A3FFC8C83C37760BE6CFD252D28940926709C723DD010E549953E3005FF91808"
        },
        "Pubkey": {
          "type": "ed25519",
          "data": "686A00033798FFA14B00C1B207C3DADF42AD122FA5F9C9D4A9BEEDB827EA9994"
        }
      }
    }
  },
  "txhash": "640BEECFF7D4035EA7C9ABCC7F83C0DCA933024C"
}
        



## /txs/recentcoin{?limit}

+ Parameters
    + limit: `2` (number)

### Query Recent Coin Tx [GET]
is to get recent coin transactions


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "tx_hash": "D5EF35C78C86F8750FDAE1FED11AE8FA811E9095",
    "time": "2018-01-26T08:23:24.709+08:00",
    "height": 1020814,
    "from": "F75D0FD7036A3BB9092DD0938BBF0A9323224832",
    "to": "01531F014238BD4A1BF9A56A458173EFCA96C95E"
  },
  {
    "tx_hash": "630DC4121836E35CCCDF804C71E49E745CE2B035",
    "time": "2018-01-26T08:02:32.266+08:00",
    "height": 1020103,
    "from": "F75D0FD7036A3BB9092DD0938BBF0A9323224832",
    "to": "F894878712E2D7179625870F4EA73A5C5AD4257E"
  }
]
        



## /txs/recentstake{?limit}

+ Parameters
    + limit: `2` (number)

### Query Recent Stake Tx [GET]
is to get recent stake transactions


+ Response 200 (text/plain; charset=utf-8)



    + Body

            [
  {
    "tx_hash": "D5EF35C78C86F8750FDAE1FED11AE8FA811E9095",
    "time": "2018-01-26T08:23:24.709+08:00",
    "height": 1020814,
    "from": "F75D0FD7036A3BB9092DD0938BBF0A9323224832",
    "to": "01531F014238BD4A1BF9A56A458173EFCA96C95E"
  },
  {
    "tx_hash": "630DC4121836E35CCCDF804C71E49E745CE2B035",
    "time": "2018-01-26T08:02:32.266+08:00",
    "height": 1020103,
    "from": "F75D0FD7036A3BB9092DD0938BBF0A9323224832",
    "to": "F894878712E2D7179625870F4EA73A5C5AD4257E"
  }
]
        



## /validators/{height}

+ Parameters
    + height: `10546` (number)

### Query Validators [GET]
is to query validators by height


+ Response 200 (text/plain; charset=utf-8)



    + Body

            {
  "block_height": 10546,
  "validators": [
    {
      "address": "3294678052AAD1648F6E0AFBCECE3BD09B402CB1",
      "pub_key": {
        "type": "ed25519",
        "data": "7A1C7CD300A797A80479FC7C717C8CEB467976775044BAFFE630DADB01F4F4D9"
      },
      "voting_power": 1000,
      "accum": -6000
    },
    {
      "address": "600AD8E3023710167C242AD1D26C4FB7AD3A3A39",
      "pub_key": {
        "type": "ed25519",
        "data": "1320BC3E22BCFDD2F9B133EBBA8BC393F9160E54917962D6E75245D885EAAD14"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "898766AF03F350D117657A7E44E54D92423F9E83",
      "pub_key": {
        "type": "ed25519",
        "data": "492DCDE8F3394A97BB92ECC3D025CEA5E380C7A04BF30991FDAF262EECC672C6"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "CA956F20A083A26BF5B9C766E95D246E0624EDC6",
      "pub_key": {
        "type": "ed25519",
        "data": "845F2C16B97D71FAF7C32724DF01A09120E4680FACFF0657977ACC852DF5E7C6"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "DC321F5C8DD94234903B53D44C1CF3B37B817950",
      "pub_key": {
        "type": "ed25519",
        "data": "0A29EF59C9B01CFC880354F83D1253FDF04B9FDCD7411B96D801B52C6F03D376"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "DD59852B326AB9AC57E3A8CAF4F00459A9539970",
      "pub_key": {
        "type": "ed25519",
        "data": "2B26539CFA678ED5AAA72C55FB6DD4B394D160DDC0478DC50654658683F53A9B"
      },
      "voting_power": 1000,
      "accum": 1000
    },
    {
      "address": "E99FA5A12168E0C4194F1324866164331A1AC2C0",
      "pub_key": {
        "type": "ed25519",
        "data": "27D710DD0FF5276651865FA6EB9B4804E46F987D1BA6A901AC35E2C0D48D7664"
      },
      "voting_power": 1000,
      "accum": 1000
    }
  ]
}
        


